name: Python Lint and Type Check

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements_test.txt
        pip install boto3 botocore
        python3 -m pip install types-requests

    - name: Check import formatting with isort
      run: isort .

    - name: Check code formatting with black
      run: black .

    - name: Check type hints with mypy
      run: mypy --explicit-package-bases data-collection-kedro/src/data_collection_kedro/pipelines/data_fusion_pipeline

    - name: Lint with pylint
      run: pylint **/*.py


