name: Python Lint and Type Check

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint isort black mypy pandas matplotlib
        pip install requests pandas pymongo python-dotenv
        python3 -m pip install pandas-stubs
        mypy --install-types

    - name: Lint with pylint
      run: pylint **/*.py

    - name: Check import formatting with isort
      run: isort .

    - name: Check code formatting with black
      run: black .
