name: Python Lint, Type Check, and Tests
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11.5'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements_test.txt
        pip install -r data-collection-kedro/requirements.txt
        pip install boto3 botocore
        python3 -m pip install types-requests
        pip install pytest pytest-cov  # Ajout de pytest et pytest-cov
        pip install pytest-mock
    - name: Check import formatting with isort
      run: isort .
    - name: Check code formatting with black
      run: black .
    - name: Lint with pylint
      run: pylint --rcfile=.pylintrc dashboard_ui/
    - name: Run tests with pytest
      run: |
        pytest --disable-warnings --maxfail=5
    - name: Generate full coverage report
      run: |
        pytest --cov=. data-collection-kedro/tests/ --cov-report=xml
        pytest --cov=. data-collection-kedro/tests/ --cov-report=html
    - name: Upload coverage report artifact
      uses: actions/upload-artifact@v3
      with:
        name: coverage-report
        path: htmlcov/
