[tool.poetry]
name = "test-docs"
version = "0.1.0"
description = ""
authors = ["keagnon <keagnon.gbe@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
cookiecutter = "^2.6.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
